/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as mainProfileRouteRouteImport } from './routes/(main)/profile/route'
import { Route as authSignUpRouteRouteImport } from './routes/(auth)/sign-up/route'
import { Route as authSignInRouteRouteImport } from './routes/(auth)/sign-in/route'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainProfileRouteRoute = mainProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => mainRouteRoute,
} as any)
const authSignUpRouteRoute = authSignUpRouteRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRouteRoute = authSignInRouteRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sign-in': typeof authSignInRouteRoute
  '/sign-up': typeof authSignUpRouteRoute
  '/profile': typeof mainProfileRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sign-in': typeof authSignInRouteRoute
  '/sign-up': typeof authSignUpRouteRoute
  '/profile': typeof mainProfileRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(main)': typeof mainRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/(auth)/sign-in': typeof authSignInRouteRoute
  '/(auth)/sign-up': typeof authSignUpRouteRoute
  '/(main)/profile': typeof mainProfileRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/sign-in' | '/sign-up' | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/sign-in' | '/sign-up' | '/profile'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(main)'
    | '/$'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(main)/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  mainRouteRoute: typeof mainRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/profile': {
      id: '/(main)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof mainProfileRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSignInRouteRoute: typeof authSignInRouteRoute
  authSignUpRouteRoute: typeof authSignUpRouteRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInRouteRoute: authSignInRouteRoute,
  authSignUpRouteRoute: authSignUpRouteRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface mainRouteRouteChildren {
  mainProfileRouteRoute: typeof mainProfileRouteRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainProfileRouteRoute: mainProfileRouteRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  mainRouteRoute: mainRouteRouteWithChildren,
  SplatRoute: SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
